### ISSUE TITLE
error in running skatMeta

### ISSUE THREAD

**Issue by elise625** [DavisBrian/seqMeta#40] opened 2018-07-20 13:26 UTC
Hello,

I'm trying to run skatMeta with prepScore results for two cohorts but ran into following error:

Error in res.numeric[ri, "p"] = p :
  number of items to replace is not a multiple of replacement length

Using this command: meta.results <- skatMeta(r_CtBMD_ECm1_may, r_CtBMD_ECm1_ger, SNPInfo = snpanno)

Not sure what else I can change to these to avoid the error?

**Comment by DavisBrian** [comment] 2018-07-20 13:59
Please provide a minimal, self-contained, and reproducible example by reducing your example as much as possible right before the problem goes away.  For a good introduction on how to make a helpful minimal reproducible example see [this StackOverflow post](https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example), or [this helpful post by Hadley]( https://gist.github.com/hadley/270442) or [this RStudio post](https://community.rstudio.com/t/faq-whats-a-reproducible-example-reprex-and-how-do-i-do-one/5219) or [this blog post]( https://www.r-bloggers.com/minimal-reproducible-examples/) By doing this, you may be able to figure out what the problem really is before reporting to me. You can attach your example as a zip file here. You may consider creating your reproducible example based on the built in seqMeta data sets.  Please include your session info with `devtools::session_info()` and the structure (`str()`) of your phenotype, genotype, and snpinfo dataset.

Usually your issue will be closed after it is fixed, but sometimes it is closed only because we are not able to offer any help. It does not mean your issue is not real or bad. You can propose a fix by yourself through a pull request. Your constructive feedback is always appreciated.

**Comment by elise625** [comment] 2018-07-20 18:04
As i was preparing an example, I ran skatMeta straight from prepScore output on one cohort and it seemed to work. Originally, I had the prepScore outputs saved and was loading it into a new document to skatMeta but this didn't seem to work for some reason.

**Comment by DavisBrian** [comment] 2018-07-20 20:45
great i'll close this.

**Closed as completed by DavisBrian** 2018-07-20 20:45 UTC
